Repository department-of-veterans-affairs/vets-json-schema, pull requests merged in 2020-07, with the labels that each got.

#446 10830 686 schema updates
  dist/686C-674-schema.json
  package.json
  src/schemas/686c-674/schema.js
Labels: vsa

#448 STEM: Update form 22-10203 submission. #7857
  dist/22-10203-schema.json
  package.json
  src/schemas/22-10203/schema.js
Labels: BAH, BAH-IR-Needed

#451 [Development] Remove Obsolete Form 526 v1
  dist/21-526EZ-schema.json
  package.json
  src/schemas/21-526EZ/schema.js
Labels: vsa

#454 Fix validation error on postal code
  dist/10-10CG-schema.json
  dist/21P-527EZ-schema.json
  dist/21P-530-schema.json
  dist/definitions.json
  package.json
  src/common/definitions.js
  src/schemas/10-10CG/schema.js
  test/common/definitions.spec.js
  test/schemas/10-10CG/schema.spec.js
  test/support/test-data.js
Labels: bug

#456 [Tech Debt] Add 526EZ schema unit tests
  test/schemas/21-526EZ/schema.spec.js
  test/support/test-data.js
Labels: vsa

#461 Temporarily restore 526EZ v1
  dist/21-526EZ-schema.json
  package.json
  src/schemas/21-526EZ/schema.js
Labels: vsa

#463 [Development] Make 526 bank routing schema
  dist/21-526EZ-ALLCLAIMS-schema.json
  package-lock.json
  package.json
  src/schemas/21-526EZ-allclaims/schema.js
  test/schemas/21-526EZ/schema.spec.js
Labels: vsa

#465 filtered out USA
  dist/686C-674-schema.json
  package.json
  src/schemas/686c-674/schema.js
Labels: vsa
