Repository department-of-veterans-affairs/vets-json-schema, pull requests merged in 2020-04, with the labels that each got.

#393 create 22-10203 schema
  dist/22-10203-schema.json
  package.json
  src/schemas/22-10203/schema.js
Labels: BAH

#396 Remove unwanted property from 10203 schema
  dist/22-10203-schema.json
  src/schemas/22-10203/schema.js
Labels: BAH, BAH-IR-Needed

#400 remove unwanted property from 10203
  dist/22-10203-schema.json
  package.json
  src/schemas/22-10203/schema.js
Labels: BAH

#395 [Tech debt] Split up constants
  src/common/address.js
  src/common/constants.js
Labels: vsa

#411 8055 use common definitions
  dist/686C-674-schema.json
  dist/constants.json
  package.json
  src/common/constants.js
  src/schemas/686c-674/schema.js
Labels: vsa

#414 7762-686-unit-tests
  dist/686C-674-schema.json
  package.json
  src/schemas/686c-674/schema.js
  test/schemas/686c-674/schema.spec.js
Labels: vsa

#419 8296-Update-property-names
  dist/686C-674-schema.json
  package.json
  src/schemas/686c-674/schema.js
  test/schemas/686c-674/schema.spec.js
Labels: vsa

#415 Fix 526 facility names regex
  src/schemas/21-526EZ-allclaims/schema.js
Labels: bug, vsa

#422 Remove `ratingDecisionId` from 526 submissions
  dist/21-526EZ-ALLCLAIMS-schema.json
  src/schemas/21-526EZ-allclaims/schema.js
Labels: bug, vsa
