Repository department-of-veterans-affairs/vets-json-schema, pull requests merged in 2020-01, with the labels that each got.

#365 Add ESLint, and Prettier formatting
  .eslintignore
  .eslintrc
  .prettierrc
  package.json
  src/common/constants.js
  src/common/definitions.js
  src/common/schema-helpers.js
  src/common/va-medical-facilities.js
  src/generate-schemas.js
  src/schemas/10-10EZ/schema.js
  src/schemas/21-526EZ-allclaims/schema.js
  src/schemas/21-526EZ/schema.js
  src/schemas/21-686C/schema.js
  src/schemas/21P-527EZ/schema.js
  src/schemas/21P-530/schema.js
  src/schemas/22-0993/schema.js
  src/schemas/22-0994/schema.js
  src/schemas/22-1990/schema.js
  src/schemas/22-1990E/schema.js
  src/schemas/22-1990N/schema.js
  src/schemas/22-1995/schema.js
  src/schemas/22-1995S/schema.js
  src/schemas/22-5490/schema.js
  src/schemas/22-5495/schema.js
  src/schemas/24-0296/schema.js
  src/schemas/28-1900/schema.js
  src/schemas/28-8832/schema.js
  src/schemas/40-10007/schema.js
  src/schemas/FEEDBACK-TOOL/schema.js
  src/schemas/VIC/schema.js
  src/start.js
  src/watch.js
  test/schemas/24-0296/schema.spec.js
  yarn.lock
Labels: ready

#367 4494 686c schema updates
  dist/21-686C-schema.json
  dist/definitions.json
  package.json
  src/common/definitions.js
  src/schemas/21-686C/schema.js
  test/schemas/21-686C/schema.spec.js
  test/support/schema-test-helper.js
Labels: vsa

#369 Add schema for HLR form 20-0996
  .gitignore
  dist/20-0996-schema.json
  src/schemas/20-0996/schema.js
  test/schemas/20-0996/schema.spec.js
  test/support/schema-test-helper.js
Labels: WIP, vsa

#373 add new properties and unit tests to 686c
  dist/21-686C-schema.json
  package.json
  src/schemas/21-686C/schema.js
  test/schemas/21-686C/schema.spec.js
Labels: vsa

#375 Mc revert 686 schema changes
  dist/21-686C-schema.json
  package.json
  src/schemas/21-686C/schema.js
  test/schemas/21-686C/schema.spec.js
Labels: vsa

#376 Remove REAP option from 1995 schema
  dist/22-1995-schema.json
  dist/22-1995S-schema.json
  package.json
  src/schemas/22-1995/schema.js
  src/schemas/22-1995S/schema.js
Labels: BAH, BAH-IR-Needed
