Repository department-of-veterans-affairs/vets-json-schema, pull requests merged in 2020-09, with the labels that each got.

#492 Refactor Tests That Validate Schema Against Example JSON
  dist/CREATE_HLR_422_RESPONSE-schema.json
  package.json
  src/examples.js
  src/generate-schemas.js
  src/schemas/create_hlr_200_response/examples/example.json
  src/schemas/create_hlr_422_response/examples/invalid/source_is_true.json
  src/schemas/create_hlr_422_response/examples/valid/source_is_false.json
  src/schemas/create_hlr_422_response/examples/valid/source_is_string.json
  src/schemas/create_hlr_422_response/schema.js
  test/schemas/create_hlr_200_response/schema.spec.js
  test/schemas/create_hlr_422_response/schema.spec.js
  test/support/validate-examples-against-schema.js
Labels: vsa

#497 [Tech debt] Fix state sorting
  dist/21-526EZ-ALLCLAIMS-schema.json
  dist/22-0994-schema.json
  dist/constants.json
  package.json
  src/common/address.js
Labels: vsa

#494 Fix email minLength
  dist/0873-schema.json
  dist/10-10CG-schema.json
  dist/22-10203-schema.json
  dist/686C-674-schema.json
  dist/COVID-VACCINE-TRIAL-schema.json
  dist/MDOT-schema.json
  dist/definitions.json
  package.json
  src/common/definitions.js
Labels: bug, vsa

#498 12826 add ssn dob to 686 properties
  dist/686C-674-schema.json
  package.json
  src/schemas/686c-674/schema.js
Labels: vsa

#506 use 10.1.0 in package-lock.json
  package-lock.json
Labels: vsa

#507 Remove 1995S Schema
  dist/22-1995S-schema.json
  package.json
  src/schemas/22-1995S/schema.js
Labels: BAH

#521 13784: Add receiveTexts to 10203 schema
  dist/22-10203-schema.json
  package.json
  src/schemas/22-10203/schema.js
Labels: BAH, BAH-IR-Needed
